// Generated by gencpp from file l_service/Person.msg
// DO NOT EDIT!


#ifndef L_SERVICE_MESSAGE_PERSON_H
#define L_SERVICE_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <l_service/PersonRequest.h>
#include <l_service/PersonResponse.h>


namespace l_service
{

struct Person
{

typedef PersonRequest Request;
typedef PersonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person
} // namespace l_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::l_service::Person > {
  static const char* value()
  {
    return "9495c620750744a2177d2501849849d0";
  }

  static const char* value(const ::l_service::Person&) { return value(); }
};

template<>
struct DataType< ::l_service::Person > {
  static const char* value()
  {
    return "l_service/Person";
  }

  static const char* value(const ::l_service::Person&) { return value(); }
};


// service_traits::MD5Sum< ::l_service::PersonRequest> should match
// service_traits::MD5Sum< ::l_service::Person >
template<>
struct MD5Sum< ::l_service::PersonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::l_service::Person >::value();
  }
  static const char* value(const ::l_service::PersonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::l_service::PersonRequest> should match
// service_traits::DataType< ::l_service::Person >
template<>
struct DataType< ::l_service::PersonRequest>
{
  static const char* value()
  {
    return DataType< ::l_service::Person >::value();
  }
  static const char* value(const ::l_service::PersonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::l_service::PersonResponse> should match
// service_traits::MD5Sum< ::l_service::Person >
template<>
struct MD5Sum< ::l_service::PersonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::l_service::Person >::value();
  }
  static const char* value(const ::l_service::PersonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::l_service::PersonResponse> should match
// service_traits::DataType< ::l_service::Person >
template<>
struct DataType< ::l_service::PersonResponse>
{
  static const char* value()
  {
    return DataType< ::l_service::Person >::value();
  }
  static const char* value(const ::l_service::PersonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // L_SERVICE_MESSAGE_PERSON_H
